class Calculadora(val a: Int, val b:Int) {
   fun somar(a: Int, b: Int): Int {
	return a + b
	}
	val resultado = somar(4, 2) 
    
    fun subtrair(a: Int, b: Int): Int {
	return a - b
	}
	val resultado = somar(4, 2) 
    
    fun multiplicar(a: Int, b: Int): Int {
	return a * b
	}
	val resultado = somar(4, 2) 
    
    fun dividir(a: Int, b: Int): Int {
	return a / b
	}
	val resultado = somar(4, 2) 
    
